#!/bin/bash

echo "🔍 Cómo obtener tu Project ID de Supabase"
echo "=========================================="
echo ""
echo "Opción 1 - Desde el Dashboard:"
echo "------------------------------"
echo "1. Ve a https://supabase.com/dashboard"
echo "2. Selecciona tu proyecto"
echo "3. Ve a: Settings (Configuración) → General"
echo "4. Busca 'Reference ID' o 'Project ID'"
echo "5. Copia ese ID (tiene formato: abcdefghijklmnopqrst)"
echo ""
echo "Opción 2 - Desde la URL:"
echo "------------------------"
echo "Cuando estés en tu proyecto, la URL será algo como:"
echo "https://supabase.com/dashboard/project/AQUI_ESTA_TU_ID"
echo ""
echo "Opción 3 - Desde Project Settings → API:"
echo "-----------------------------------------"
echo "1. Ve a Settings → API"
echo "2. Busca 'Project URL'"
echo "3. El ID está en la URL: https://ESTE_ES_TU_ID.supabase.co"
echo ""
echo "📝 Luego ejecuta:"
echo "npx supabase gen types typescript --project-id TU_ID_REAL > src/lib/types/database.types.ts"
echo ""
echo "Ejemplo:"
echo "npx supabase gen types typescript --project-id xyzabcdefghijk > src/lib/types/database.types.ts"
echo ""
